In [45]:
import numpy as np
import pandas as pd
import nltk
nltk.download('punkt')
nltk.download('wordnet')
from nltk import word_tokenize

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


# Lab Task 01

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [92]:
#code here
oneD = np.arange(12)
print('1d', oneD)
twoD = oneD.reshape((3,4))
print('2d', twoD)

a = np.arange(10)
b = np.arange(10)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

1d [ 0  1  2  3  4  5  6  7  8  9 10 11]
2d [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]


# Lab Task 02


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [15]:
from nltk.corpus import wordnet

def get_syns(words):
    result = []
    for word in words:
        synonyms = []
        for syn in wordnet.synsets(word):
            for lemma in syn.lemmas():
                synonyms.append(lemma.name())
        result.extend(synonyms)
    return set(result)

In [48]:
def classify_mails(emails):

  prm = ["sale", "deal", "discount", "promotion", "special offer", "exclusive", "clearance", "new arrival", "limited time", "bonus", 'claim']
  spm = ["free", "prize", "discount", "win", "limited time", "money", "click here", "act now", "offer", "guaranteed"]
  ip = ["urgent", "important", "action required", "deadline", "critical", "response needed", "attention", "priority", "confidential", "emergency"]

  promo = get_syns(prm)
  spam = get_syns(spm)
  imp = get_syns(ip)
  result = []
  for email in emails:
    pword_count = 0
    iword_count = 0
    sword_count = 0

    for word in word_tokenize(email):
      if word in promo:
        pword_count += 1
      elif word in spam:
        sword_count += 1
      elif word in imp:
        iword_count += 1

    max_dict = {'Promotion': pword_count, 'Spam': sword_count, 'Important': iword_count}
    result.append(max(max_dict, key=max_dict.get))
    # print('mmmm',max_dict)
  return result





In [49]:

i = """
We hope this email finds you well. We wanted to remind you about the upcoming conference scheduled for next week.
Your presence is crucial, and we need your confirmation as soon as possible.
Please take a moment to confirm your attendance by clicking on the following link: [Confirmation Link].
If you have any questions or concerns, feel free to reach out to us.
Thank you for your prompt attention to this matter.
"""
p = """
Exciting news! We're thrilled to announce a special promotion exclusively for our loyal customers.
For a limited time only, enjoy a 50% discount on all our new arrivals.
Hurry, this offer won't last long! Visit our website or stop by our store to explore our latest collection.
Don't miss out on this fantastic opportunity to refresh your wardrobe for less.
"""
s = """
We are thrilled to inform you that you've been selected as the grand prize winner of our exclusive sweepstakes. You have won a whopping $1,000,000!
To claim your prize, simply click on the link below and provide your personal information. Act now to secure your winnings!
Claim Your Prize Now: [Claim Link]
Congratulations again on your incredible win!
"""
rs = classify_mails([i,s,p])
rs

mmmm {'Promotion': 1, 'Spam': 1, 'Important': 2}
mmmm {'Promotion': 2, 'Spam': 6, 'Important': 0}
mmmm {'Promotion': 2, 'Spam': 1, 'Important': 0}


['Important', 'Spam', 'Promotion']

In [36]:
print(promo)

{'manage', 'scoop', 'peck', 'make_do', 'contend', 'deal_out', 'good_deal', 'get_by', 'brush_aside', 'discount_rate', 'great_deal', 'parcel_out', 'passel', 'stack', 'wad', 'rebate', 'conduct', 'handle', 'muckle', 'look_at', 'discount', 'sales_agreement', 'advancement', 'hand', 'address', 'grapple', 'dismiss', 'furtherance', 'forwarding', 'exclusive', 'share', 'brush_off', 'promotion', 'mass', 'administer', 'make_out', 'headroom', 'business_deal', 'slew', 'single', 'undivided', 'claim', 'bank_discount', 'sell', 'mint', 'arrogate', 'sight', 'heap', 'flock', 'mountain', 'batch', 'cover', 'push_aside', 'clearance', 'raft', 'care', 'packaging', 'dish_out', 'pot', 'title', 'lot', 'spate', 'softwood', 'disregard', 'incentive', 'apportion', 'exact', 'price_reduction', 'distribute', 'shell_out', 'bonus', 'promotional_material', 'bargain', 'treat', 'sale', 'portion_out', 'plenty', 'dole_out', 'fillip', 'cut-rate_sale', 'carry_on', 'call', 'cope', 'deal', 'take', 'dispense', 'lay_claim', 'consider

# Lab Task 03

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [55]:
#code here
dct = {'hello': 'hola', 'goodbye': 'adiós', 'thank you': 'gracias', 'yes': 'sí', 'no': 'no', 'cat': 'gato', 'dog': 'perro', 'house': 'casa', 'friend': 'amigo', 'love': 'amor'}
exit = 'q'
while True:
  inp = input('Please enter an English word for Spanish translation (press q to quit): ')
  inp = inp.lower()
  if inp == exit:
    break
  eng = dct.keys()
  if inp in eng:
    print(dct[inp])
  else:
    print('Translation is not available')


Please enter an English word for Spanish translation (press q to quit): hello
hola
Please enter an English word for Spanish translation (press q to quit): goodbye
adiós
Please enter an English word for Spanish translation (press q to quit): adios
Translation is not available
Please enter an English word for Spanish translation (press q to quit): si
Translation is not available
Please enter an English word for Spanish translation (press q to quit): yes
sí
Please enter an English word for Spanish translation (press q to quit): q


# Lab Task 04

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

Some tree example

In [71]:
df = pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')

global_sum = df['Global_Sales'].sum()
print('global sales sum',global_sum)

global_max = df['Global_Sales'].max()
print('global sales max',global_max)

nu_avg = df['NA_Sales'].mean()
eu_avg = df['EU_Sales'].mean()
jp_avg = df['JP_Sales'].mean()
other_avg = df['Other_Sales'].mean()
print()
print(f"Average NA Sales: {nu_avg}")
print(f"Average EU Sales: {eu_avg}")
print(f"Average JP Sales: {jp_avg}")
print(f"Average Other Sales: {other_avg}")


global sales sum 8920.44
global sales max 82.74

Average NA Sales: 0.26466742981082064
Average EU Sales: 0.14665200626581515
Average JP Sales: 0.077781660441017
Average Other Sales: 0.0480630196409206


In [72]:

popular_5 = df.nlargest(5, 'Global_Sales')
print('top 5: ' )
popular_5


top 5: 


Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo   
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo   
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo   
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo   
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo   

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales  
0     41.49     29.02      3.77         8.46         82.74  
1     29.08      3.58      6.81         0.77         40.24  
2     15.85     12.88      3.79         3.31         35.82  
3     15.75     11.01      3.28         2.96         33.00  
4     11.27      8.89     10.22         1.00         31.37

In [80]:
nu_total = df['NA_Sales'].sum()
eu_total = df['EU_Sales'].sum()
jp_total = df['JP_Sales'].sum()
other_total = df['Other_Sales'].sum()
print(f"Total NA Sales: {nu_total}")
print(f"Total EU Sales: {eu_total}")
print(f"Total JP Sales: {jp_total}")
print(f"Total Other Sales: {other_total}")

sales = df.groupby('Genre')['NA_Sales'].sum()
genre_popular = sales.idxmax()
print('popular genre in NA: ', genre_popular)
print()

df.tail(10)

Total NA Sales: 4392.950000000001
Total EU Sales: 2434.1299999999997
Total JP Sales: 1291.0200000000002
Total Other Sales: 797.7500000000001
popular genre in NA:  Action



Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01      0.00   
16589  2016.0        Action        dramatic create      0.00      0.00   
16590  2007.0  Role-Playing     Falcom Corporation      0.00      0.00   
16591  2004.0     Adventure                Ubisoft      0.01      0.00   
16592  2008.0    Simulation              Destineer      0.01      0.00   
16593  2002.0      Platform                  Kemco      0.01      0.00   
16594  2003.0       Shooter             Infogrames      0.01      0.00   
16595  2008.0        Racing             Activision      0.00      0.00   
16596  2010.0        Puzzle               7G//AMES      0.00      0.01   
16597  2003.0      Platform                Wanadoo      0.01      0.00   

       JP_Sales  Other_Sales  Global_Sales  
16588      0.00          0.0          0.01  
16589      0.01          0.0          0.01  
16590      0.01          0.0          0.01  
16591      0.00          0.0          0.01  
16592      0.00          0.0          0.01  
16593      0.00          0.0          0.01  
16594      0.00          0.0          0.01  
16595      0.00          0.0          0.01  
16596      0.00          0.0          0.01  
16597      0.00          0.0          0.01

In [96]:
global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
global_sales
for p, i in global_sales.groupby(level=0):
    print(p)

print()
genre_sales = df.groupby('Genre')['Global_Sales'].sum()
total = df['Global_Sales'].sum()
market_share = (genre_sales / total) * 100
print("Market share\n",market_share)
print()

crltn = df['NA_Sales'].corr(df['EU_Sales'])
print('correlation: ', crltn)

PS2
PS3
X360

Market share
 Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

correlation:  0.7677267483702631


In [63]:
df

Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [57]:
# import pandas as pd

# # Create a DataFrame to represent a tree
# data = {
#     'node': ['A', 'B', 'C', 'D', 'E', 'F'],
#     'parent': [None, 'A', 'A', 'B', 'B', 'C']
# }
# df = pd.DataFrame(data)

# print(df)


In [ ]:
# pip install networkx


In [ ]:
# import pandas as pd
# import networkx as nx
# import matplotlib.pyplot as plt

# # Create a DataFrame representing edges in a graph
# data = {
#     'from': ['A', 'A', 'B', 'C', 'D'],
#     'to': ['B', 'C', 'D', 'E', 'E']
# }
# edges = pd.DataFrame(data)

# # Create a graph from the edges DataFrame
# G = nx.from_pandas_edgelist(edges, 'from', 'to')

# # Draw the graph
# nx.draw(G, with_labels=True)
# plt.show()

# # Analyze the graph
# print("Nodes:", G.nodes())
# print("Edges:", G.edges())
# print("Degree for each Node:", dict(G.degree()))
